name: sparsax
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - scipy
  - numpy
  - jax
  - scikit-sparse
  - nanobind
  - suitesparse
  - cmake
  - scikit-build-core
  - pytest
  - cxx-compiler
  - pytensor
