name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * 1,4"

jobs:
  Test:
    name: ${{ matrix.os }}, ${{ matrix.environment-file }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        environment-file:
          - ci/312.yml
          - ci/313.yml
          - ci/314.yml
        include:
          - environment-file: ci/313.yml
            os: macos-latest
          - environment-file: ci/313.yml
            os: windows-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: 'latest'

      - name: Install package
        run: pip install -e .  --no-build-isolation --no-deps

      - name: Test package
        run: |
          pytest --cov src/sparsax \
           -v \
           -r a \
           -n auto \
           --color yes \
           --cov src \
           --cov-append \
           --cov-report term-missing \
           --cov-report xml \
           tests
      - name: codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: cholax-codecov

      - name: Generate and publish the report
        if: |
          failure()
          && steps.status.outcome == 'failure'
          && github.event_name == 'schedule'
          && github.repository_owner == 'knaaptime'
        uses: xarray-contrib/issue-from-pytest-log@v1
        with:
          log-path: pytest-log.jsonl
